version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: sudo apt-get update -y  && sudo apt-get install nodejs -y

      - run:
          name: cloning github
          command: git clone https://github.com/helloworld-8000/streaming3.git && cd streaming3 
      
      - run:
          name: Install Node.js dependencies
          command: npm install && npm install pm2 -g


      
      # Store .env file
      - run:
          name: Store .env file
          command: echo 'streamkey=84tc-93q4-mapa-m0kv-9c1m' > .env

      # Run your Node.js app
      - run:
          name: Run Your Node.js App
          command: pm2 start main.js  # Replace with your Node.js application's entry point


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
